spring.application.name=redis-session

# redis set up automatically, no properties needed. it will save session data

# keep docker container running when application is stopped/restarted
spring.docker.compose.lifecycle-management=start_only